version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: node:16.5.0-buster-slim
  resource_class: small

jobs:
  npm-install:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: npm install
          command: | 
            npm install
            npm install --no-save
      - persist_to_workspace:
          root: .
          paths:
             - .
  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: lint
          command: npm run fmt_test

  test-types:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test types
          command: npm run test:types

  test-unit:
    docker:
      - image: cypress/node14.17.0-chrome91-ff89
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build bundle
          command: npm run build
      - run:
          name: Run tests
          command: npm run test:unit

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - npm-install
      - lint:
          requires:
            - npm-install
      - test-types:
          requires:
            - npm-install
      - test-unit:
          requires:
            - npm-install
