version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: node:16.5.0-buster-slim
  resource_class: small

jobs:
  npm-install:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: npm install
          command: | 
            npm install
            npm install --no-save
      - persist_to_workspace:
          root: .
          paths:
             - .
  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: lint
          command: npm run fmt_test
  
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build main bundle
          command: npm run test

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - npm-install
      - lint:
          requires:
            - npm-install
      - test:
          requires:
            - npm-install
