version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: node:16.5.0-buster-slim
  resource_class: small

jobs:
  npm-install:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: npm install
          command: | 
            npm install
            npm install --no-save
      - persist_to_workspace:
          root: .
          paths:
             - .
  lint:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: lint
          command: npx prettier -l './*.{mjs,js,ts,md,json,html}' './{src,docs,tests}/{**/,}*.{mjs,js,ts,md,json,html}'

  test-types:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test types
          command: npm run test:types

  test-unit:
    environment: 
      - IN_DOCKER: 1
    docker:
      - image: cypress/browsers:node14.17.0-chrome91-ff89
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build bundle
          command: npm run build
      - run:
          name: Run tests
          command: npx karma start karma start
      - store_test_results:
          path: test-results

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - npm-install
      - lint
      - test-types:
          requires:
            - npm-install
      - test-unit:
          requires:
            - npm-install
